# Generated by Django 6.0.3 on 2026-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brother',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='brother',
            name='grad_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brother',
            name='initiation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='last_name',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brother',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
